### ISSUE TITLE
Broken colours in System settings

### ISSUE THREAD

**Issue by Yersi88** [HimDek/Utterly-Nord-Plasma#11]
I have applied he kvantum theme and the Utterly-Nord colour scheme in system settings. However, the system settings look like this: 

![image](https://github.com/HimDek/Utterly-Nord-Plasma/assets/77145281/0f63071e-a3c1-429c-9033-722313bfb85e)

Any fix for this? Plasma 5.27.9 

Many thanks!

**Comment by HimDek** [comment]
Thats what its supposed to look like.

**Comment by Yersi88** [comment]
Ah, I thought the left side and top where it says 'Window Behavior" should also be transparent.

**Comment by HimDek** [comment]
> Ah, I thought the left side and top where it says 'Window Behavior" should also be transparent.

Not possible because those elements just can't be transparent. Just a limitation of how the System Settings application has been build.
