### ISSUE TITLE
AUR deployments

### ISSUE THREAD

**Issue by jorgebodega** [HimDek/Utterly-Nord-Plasma#2]
Hello!

I reach this package looking for some themes for my SDDM installations, and I think this one really looks amazing!

Do you have any plans about automatic deployments on releases or about? I prefer to have control through `pacman` instead of downloading every single time.

I can try to help, if you want.

Cheers!

**Comment by HimDek** [comment]
If you have the knowledge, you can release it in the aur but I don't want to maintain it.
