### ISSUE TITLE
How to make the panel look like this in README

### ISSUE THREAD

**Issue by Firestar-Reimu** [HimDek/Utterly-Nord-Plasma#3]
I really like this panel on README.md:
![Screenshot_20221013_150449](https://user-images.githubusercontent.com/65082432/195528794-24649313-e420-4763-bbb8-0d42c3d9d3dc.png)
But my panel here looks like:
![Screenshot_20221013_152118](https://user-images.githubusercontent.com/65082432/195528968-277fe2c8-c373-498d-9371-e860ad628454.png)
which the icons are too small and I think the under-bar can be replaced by background color
How to make the panel look like [this](https://github.com/HimDek/Utterly-Nord-Plasma/blob/master/assets/20220916_170516_Screenshot_88.png)

**Comment by HimDek** [comment]
Other than the icons, they look the same to me...
Just use Tela Circle Icons (Nord variant) from [KDE Store](https://store.kde.org)
