### ISSUE TITLE
System Settings crash with that theme

### ISSUE THREAD

**Issue by master-of-zen** [HimDek/Utterly-Nord-Plasma#5]
Love it. Only issue that recently after system upgrade, system apps and settings started to crash with Utterly Kvantum themes.
I can reproduce it 100% of the time. Doesn't have with any other kvantum themes that i tried.
It results in segmentation fault. I'm not sure that it's because of the theme

**Comment by HimDek** [comment]
This issue might take some time for me to reproduce. Please tell me which Distro, version of plasma you are using.

**Comment by master-of-zen** [comment]
Here is example:
>Go to settings, check tabs
>Change kvantum theme to utterly(any of them)
>Most of system settings tabs crash
>Can't "open terminal here" in dolphin

https://user-images.githubusercontent.com/46526140/214479039-1713089c-c9ba-4b81-b936-a232f800e0d3.mp4

**Comment by master-of-zen** [comment]
```
Kvantum Manager 1.0.8
Arch
KDE Plasma 5.26.5
KDE Frameworks: 5.102.0
Qt: 5.15.8
Kernel 6.1.7-arch1-1
Wayland
```

**Comment by master-of-zen** [comment]
I completely uninstalled all kvanum related packages, and installed current upstream `Kvantum Manager 1.0.7` and issue is gone)
Sorry for bothering, peace
