### ISSUE TITLE
Big windows borders under fractional scaling

### ISSUE THREAD

**Issue by lenglingxuan** [HimDek/Utterly-Nord-Plasma#6]
I really love the theme. It's one of the best themes I've ever seen. But I find that windows borders is very big. After googling about it, I find it's due to fractional scaling. So could you please add special versions for fractional scaling like [this theme](https://github.com/vinceliuice/WhiteSur-kde/issues/15)? By the way, I'm using a 1.75x fractional scaling.
![image](https://user-images.githubusercontent.com/112380251/217684483-afec3d88-5a74-4ec2-aece-2eb77accff61.png)

**Comment by HimDek** [comment]
Referred to https://github.com/HimDek/Utterly-Round-Plasma-Style/issues/3

The aurorae (Window decoration) themes for all Utterly Plasma themes are present in [Utterly Round Plasma](https://github.com/HimDek/Utterly-Round-Plasma-Style). This issue will continue there.
