### ISSUE TITLE
Hard to see the words when background is white

### ISSUE THREAD

**Issue by lenglingxuan** [HimDek/Utterly-Nord-Plasma#7]
Sometimes I'm using chrome and I open the terminal to try something that I learn. But since the background is white, the words on the title bar of the window is hard to see, which is a little bit annoying for me. So could you adjust the opacity or something a little so that the theme can perform better under these special circumstances? (I have turned the background contrast on)
Screen shot is as below:
![image](https://user-images.githubusercontent.com/112380251/217687366-96c7e593-7930-4be0-b4b5-82713fe8946e.png)

**Comment by HimDek** [comment]
Referred to https://github.com/HimDek/Utterly-Round-Plasma-Style/issues/2
